export const GET_ENTRIES_START = "[ENTRIES] START GET ALL ENTRIES";
export const GET_ENTRIES_SUCCESS = "[ENTRIES] GET ALL ENTRIES SUCCESS";
export const GET_ENTRIES_FAILURE = "[ENTRIES] GET ALL ENTRIES FAILURE";
export const GET_ACCOUNTS_START = "[ACCOUNTS] START GET ALL ACCOUNTS";
export const GET_ACCOUNTS_SUCCESS = "[ACCOUNTS] GET ALL ACCOUNTS SUCCESS";
export const GET_ACCOUNTS_FAILURE = "[ACCOUNTS] GET ALL ACCOUNTS FAILURE";
