export const GET_ENTRIES_START = "[ENTRIES] START GET ALL ENTRIES";
export const GET_ENTRIES_SUCCESS = "[ENTRIES] GET ALL ENTRIES SUCCESS";
export const GET_ENTRIES_FAILURE = "[ENTRIES] GET ALL ENTRIES FAILURE";
