export const GET_PRODUCTS_START = "[PRODUCT_CONGIF] START GET ALL PRODUCTS";
export const GET_PRODUCTS_SUCCESS = "[PRODUCT_CONGIF] GET ALL PRODUCTS SUCCESS";
export const GET_PRODUCTS_FAILURE = "[PRODUCT_CONGIF] GET ALL PRODUCTS FAILURE";