export const GETAZPROFILESUCCESS = '[AZURE LOGIN] GET AZURE AD PROFILE SUCCESS';
export const GETAZPROFILEFAILURE = '[AZURE LOGIN] GET AZURE AD PROFILE FAILURE';
export const GETAZPROFILEIMAGESUCCESS = '[AZURE LOGIN] GET AZURE AD PROFILE IMAGE SUCCESS';
export const GETAZPROFILEIMAGEFAILURE = '[AZURE LOGIN] GET AZURE AD PROFILE IMAGE FAILURE';
export const SETAZADACCESSTOKEN = '[AZURE LOGIN] SET AZURE AD ACCESSS TOKEN SUCCESS';
export const SETGRAPHTOKEN = '[AZURE LOGIN] SET AZURE GRAPH ACCESSS TOKEN SUCCESS';
export const RESETSTATE = '[AZURE LOGIN] RESET STATE';
