export const GETAZPROFILESUCCESS = '[AZURE LOGIN] GET AZURE AD PROFILE SUCCESS';
export const GETAZPROFILEFAILURE = '[AZURE LOGIN] GET AZURE AD PROFILE FAILURE';
export const GETAZPROFILEIMAGESUCCESS = '[AZURE LOGIN] GET AZURE AD PROFILE IMAGE SUCCESS';
export const GETAZPROFILEIMAGEFAILURE = '[AZURE LOGIN] GET AZURE AD PROFILE IMAGE FAILURE';